# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SCLLJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SCLLJ

	pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.4.1'
  pod 'MBProgressHUD', '~> 1.2.0'
	pod 'YTKKeyValueStore', '~> 0.1.2'


end
